export const APP_NAME = "Intelink";
export const APP_VERSION = "1.0.0";

export const COLORS = {
	primary: "#3B82F6",
	secondary: "#6B7280",
	success: "#10B981",
	warning: "#F59E0B",
	error: "#EF4444",
	info: "#3B82F6",
	gray: {
		50: "#F9FAFB",
		100: "#F3F4F6",
		200: "#E5E7EB",
		300: "#D1D5DB",
		400: "#9CA3AF",
		500: "#6B7280",
		600: "#4B5563",
		700: "#374151",
		800: "#1F2937",
		900: "#111827",
	},
};

export const SPACING = {
	xs: 4,
	sm: 8,
	md: 16,
	lg: 24,
	xl: 32,
	xxl: 48,
};

export const BORDER_RADIUS = {
	sm: 4,
	md: 8,
	lg: 12,
	xl: 16,
	xxl: 24,
};

export const FONT_SIZES = {
	xs: 12,
	sm: 14,
	md: 16,
	lg: 18,
	xl: 20,
	xxl: 24,
	xxxl: 32,
};

export const COUNTRY_NAMES: Record<string, string> = {
	CN: "China",
	CA: "Canada",
	TH: "Thailand",
	VN: "Vietnam",
	BR: "Brazil",
	PH: "Philippines",
	AU: "Australia",
	JP: "Japan",
	MY: "Malaysia",
	US: "United States",
	UK: "United Kingdom",
	GB: "United Kingdom",
	DE: "Germany",
	FR: "France",
	IN: "India",
	KR: "South Korea",
	SG: "Singapore",
	ID: "Indonesia",
	RU: "Russia",
	IT: "Italy",
	ES: "Spain",
	MX: "Mexico",
	NL: "Netherlands",
	SE: "Sweden",
	CH: "Switzerland",
	BE: "Belgium",
	AT: "Austria",
	NO: "Norway",
	DK: "Denmark",
	FI: "Finland",
	PL: "Poland",
	TR: "Turkey",
	SA: "Saudi Arabia",
	AE: "United Arab Emirates",
	ZA: "South Africa",
	EG: "Egypt",
	AR: "Argentina",
	CL: "Chile",
	CO: "Colombia",
	PE: "Peru",
	NZ: "New Zealand",
	IE: "Ireland",
	PT: "Portugal",
	GR: "Greece",
	CZ: "Czech Republic",
	RO: "Romania",
	HU: "Hungary",
	UA: "Ukraine",
	UNKNOWN: "Unknown",
};
